name:                BrickBreaker
version:             0.1.0.0
github:              "gheorghitamutu/BrickBreaker"
license:             BSD3
author:              "Gheorghita Mutu"
maintainer:          "Gheorghita Mutu"
copyright:           "2020 Gheorghita Mutu"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gheorghitamutu/BrickBreaker#readme>

dependencies:
- base >= 4.7 && < 5
- sdl2
- sdl2-image
- sdl2-gfx
- sdl2-ttf
- sdl2-mixer
- linear
- mtl
- extra
- text

library:
  source-dirs: src

executables:
  BrickBreaker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - BrickBreaker
    - extra
    - mtl

tests:
  BrickBreaker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - BrickBreaker
    - extra
    - mtl
